theme: jekyll-theme-cayman
description: Souldiers Mod that tweaks some parts of the game
show_downloads: true
github:
  download_url: https://github.com/Oryss/souldiers-tweaks/releases/download/1.5.0/SouldiersTweaks.dll
mod:
  version: 1.5.0
markdown: GFM
